const sidebarStructure = [
  {
    id: "dashboard",
    title: "Dasboard",
    name: "dashboard",
    parent: true,
    icon: "dasbor",
    link: "/dashboard",
  },  
 {
    id: "marketing",
    title: "Marketing & Research",
    name: "marketing",
    parent: true,
    icon: "transaksi",
    child: [
      {
        id: "features",
        title: "Features & Highlights",
        name: "marketing.features",
        link: "/marketing/features",
        icon: "dot",
      },
      {
        id: "vendors",
        title: "Vendors",
        name: "marketing.vendors",
        link: "/marketing/vendors",
        icon: "dot",
        child: [
          {
            id: "flagships",
            title: "Flagships",
            name: "marketing.vendors.flagships",
            link: "/marketing/vendors/flagships",
            icon: "dot",
          },
          {
            id: "generic",
            title: "Generic",
            name: "marketing.vendors.generic",
            link: "/marketing/vendors/generic",
            icon: "dot",
          },
        ],
      },
      {
        id: "usp",
        title: "Unique Selling Point (USP)",
        name: "marketing.usp",
        link: "/marketing/usp",
        icon: "dot",
        child: [
          {
            id: "propositions",
            title: "propositions",
            name: "marketing.usp.propositions",
            link: "/marketing/usp/propositions",
            icon: "dot",
          },
          {
            id: "supabse",
            title: "Supabse",
            name: "marketing.usp.supabse",
            link: "/marketing/usp/supabse",
            icon: "dot",
          },
        ],
      },
    ],
  },
  {
    id: "srs",
    title: "Requirement Specifications",
    name: "srs",
    parent: true,
    icon: "pusatunduhdata",
    child: [
      {
        id: "dfd",
        title: "DFD",
        name: "srs.dfd",
        link: "/SRS/dfd",
        icon: "dot",
      },
      {
        id: "dfddocs",
        title: "DFD Docs",
        name: "srs.dfddocs",
        link: "/SRS/dfddocs",
        icon: "dot",
      },
      {
        id: "dbschema",
        title: "DB Schema",
        name: "srs.dbschema",
        link: "/SRS/dbschema",
        icon: "dot",
      },
    ],
  },
  {
    id: "development",
    title: "Development",
    name: "development",
    parent: true,
    icon: "perusahaan",
    child: [
      {
        id: "stack",
        title: "Stack",
        name: "development.stack",
        link: "/development/stack",
        icon: "dot",
      },
      {
        id: "api",
        title: "API",
        name: "development.api",
        link: "/development/api",
        icon: "dot",
        child: [
          {
            id: "laravel",
            title: "Laravel",
            name: "development.api.laravel",
            link: "/development/api/laravel",
            icon: "dot",
          },
          {
            id: "react",
            title: "React",
            name: "development.api.react",
            link: "/development/api/react",
            icon: "dot",
          },
        ],
      },
      {
        id: "database",
        title: "Database",
        name: "development.database",
        link: "/development/database",
        icon: "dot",
        child: [
          {
            id: "mysql",
            title: "Mysql",
            name: "development.database.mysql",
            link: "/development/database/mysql",
            icon: "dot",
          },
          {
            id: "supabse",
            title: "Supabse",
            name: "development.database.supabse",
            link: "/development/database/supabse",
            icon: "dot",
          },
        ],
      },
    ],
  },
  {
    id: "mou",
    title: "MOU",
    name: "mou",
    parent: true,
    icon: "mou",
    link: "/dashboard/mou",
  },
];

export { sidebarStructure };
